### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by phillips1012** [Histacom/Histacom#1]
You guys should really just do a rewrite of this. Maintaining this old code seems ridiculous to me, and a rewrite would speed up development a lot (if you start the rewrite better than the original, which seems easy considering how sloppy the current code is)

**Comment by lilyb01** [comment]
LORD | SPEAKS THE TRUTH!

But seriously, a rewrite should be done.

**Comment by jamierocks** [comment]
Yes, for 2.x.x we are considering this. Perhaps in C# or Java.

**Comment by ghost** [comment]
I'd go for Java to be honest, jamie. It's cross platform, and great, however I do need more Java knowledge... thank god YouTube exists..

**Comment by 12pearcj** [comment]
While I am for having a rewrite, I suggest we use a base code for each language; something like rewriting the command prompt in Ruby, Java, Python, C#, etc. Then the best version of the command prompt is the language we will choose! How does that sound?

**Comment by ghost** [comment]
Meh, I think we should just let the community vote.

**Comment by jamierocks** [comment]
I'd also go for Java :P

**Comment by ghost** [comment]
Yeah, however make it a GUI program using Swing. Also, Java will be harder than VB, so I need to learn more Java :P.

**Comment by jamierocks** [comment]
I don't think Swing is a very good choice for this. We should use an API like Slick2D for this.

**Comment by jamierocks** [comment]
The repo for the rewrite (for now) is at https://github.com/Histacom/HistacomRewrite. However development hasn't started yet.
